### ISSUE TITLE
Configure docker daemon to allow ecsctl exec

### ISSUE THREAD

**Issue by dynnamitt** [cxmcc/ecsctl#10]
Please forgive me since I have not tested yet and very new to ecs debugging,
 but I do not unerstand the context of "docker-daemon" [in this part of the](https://github.com/cxmcc/ecsctl#configure-docker-daemon-to-allow-ecsctl-exec) doc 
Do I modify my local dockerd or is it on the ec2 instance in aws?
The section above says "Requires customizing docker daemon to listen on internal addresses)" and further confuses me since ecs is not "internal" in my mind ...

**Comment by dynnamitt** [comment]
I did test now agaist my fargate cluster and:
-----------------------------------------------------------------
ecsctl exec -it 358610a53af14334ad440d95b08c5e5a  --cluster gitlab-runner-cluster
Traceback (most recent call last):
  File "/home/kjetil/.local/bin/ecsctl", line 8, in <module>
    sys.exit(main())
  File "/home/kjetil/.local/lib/python3.8/site-packages/ecsctl/__main__.py", line 6, in main
    cli(obj=default_config)
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kjetil/.local/lib/python3.8/site-packages/ecsctl/cmds.py", line 220, in exec_command
    pty.exec_command()
  File "/home/kjetil/.local/lib/python3.8/site-packages/ecsctl/pty.py", line 49, in exec_command
    first_container_name, hostname, container_id = self.get_ecs_hostname_of_task()
  File "/home/kjetil/.local/lib/python3.8/site-packages/ecsctl/pty.py", line 26, in get_ecs_hostname_of_task
    raise Exception('"exec" does not work with FARGATE.')
Exception: "exec" does not work with FARGATE.

**Comment by cxmcc** [comment]
Fargate doesn't support exec in any simple/normal way.

**Comment by cxmcc** [comment]
They are planning to support it natively at some point, but not implemented yet. See: https://github.com/aws/containers-roadmap/issues/1050

**Comment by MrChrisRodriguez** [comment]
Fargate now supports exec. Should this be re-opened?
