### ISSUE TITLE
ImportError: No module named ssl_match_hostname

### ISSUE THREAD

**Issue by lmancilla** [cxmcc/ecsctl#2]
Hello, I had problems when executing this command

ecsctl get nodes

`Traceback (most recent call last):
  File "/usr/local/bin/ecsctl", line 7, in <module>
    from ecsctl.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/ecsctl/__main__.py", line 1, in <module>
    from .cmds import cli
  File "/usr/local/lib/python2.7/dist-packages/ecsctl/cmds.py", line 7, in <module>
    from .pty import Pty
  File "/usr/local/lib/python2.7/dist-packages/ecsctl/pty.py", line 2, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 11, in <module>
    from . import api
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/docker/ssladapter/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname`

I tried reinstalling backports.ssl-match-hostname package but nothing :(

Ubuntu 16.04 LTS

**Comment by cxmcc** [comment]
@lmancilla Could you show me the output of your `pip freeze` command. I suspect there are library version issues. I just added version pinning here: https://github.com/cxmcc/ecsctl/commit/8335472489bca7c2e6d47ac0ee9105cbb8b5d0c0

**Comment by lmancilla** [comment]
@cxmcc It's working now with https://github.com/cxmcc/ecsctl/commit/8335472489bca7c2e6d47ac0ee9105cbb8b5d0c0

Thanks!!
