### ISSUE TITLE
ecsctl exec giving KeyError: 'containerInstanceArn'

### ISSUE THREAD

**Issue by DrSahoo** [cxmcc/ecsctl#6]
Does ecsctl support fargate tasks right now? I will appreciate of you can help with this issue.

"ecsctl exec --cluster test1 xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx date" gives the following error on a fargate task:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ecsctl", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ecsctl/__main__.py", line 6, in main
    cli(obj=default_config)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ecsctl/cmds.py", line 220, in exec_command
    pty.exec_command()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ecsctl/pty.py", line 46, in exec_command
    first_container_name, hostname = self.get_ecs_hostname_of_task()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/ecsctl/pty.py", line 24, in get_ecs_hostname_of_task
    container_instance = info['containerInstanceArn']
KeyError: 'containerInstanceArn'

**Comment by cxmcc** [comment]
Running exec on farget will likely not working. because Fargate does not expose underlying hosts to users.
